---
- name: Ping test for linux clients
  hosts: all
  gather_facts: True
  become: yes
  tasks:
    - name: ping
      ping:

    - name: Set os_patching directory path
      set_fact:
        os_patching_folder: ajinkyagadge/directory2

    - name: Create os_patching directory
      file:
        path: "{{ os_patching_folder }}"
        state: directory
        recurse: yes

   # - name: Copy the template file
   #   template:
   #     src: ajinkyagadge/clear-softwaredistribution.ps1.j2  # Assuming you have a Jinja2 template file
   #     dest: "{{ os_patching_folder }}/clear-softwaredistribution.ps1"
   #   vars:
   #     os_patching: "{{ os_patching }}"  # Assuming os_patching is defined in your Ansible variables
   
    - name: Copy the clear-softwaredistribution.ps1 script
      copy:
        src: ajinkyagadge/clear-softwaredistribution.ps1.j2                                    # Source directory containing the script template
        dest: "{{ os_patching_folder }}/clear-softwaredistribution.ps1"
        remote_src: yes
        mode: '0664'
        
