---
- name: Ping test for linux clients
  hosts: all
  gather_facts: True
  become: yes
  tasks:
    - name: ping
      ping:

    - name: Set os_patching directory path
      set_fact:
        os_patching_folder: ajinkyagadge/directory1

    - name: Create os_patching directory
      file:
        path: "{{ os_patching_folder }}"
        state: directory
        recurse: yes
