- name: Ping test for windows clients
  hosts: all
  gather_facts: False
  #become: yes

  vars_files:
    - ./vars/ext_vars.yml  
  
  tasks:
    - name: ping
      win_ping:
    
    - name: Print File name
      ansible.builtin.debug:
        msg: "File Path1: {{ project_folder }}"
        msg: "File Path2: {{ os_patching_folder }}"

    - name: Create os_patching directory
      win_file:
        path: "{{ os_patching_folder }}"
        state: directory
        recurse: yes

    - name: Create certificates directory and chek it exists or not
      ansible.windows.win_file:
        path: "{{ certificates_folder }}"
        state: directory
      when: certificates_folder is defined and certificates_folder is not none

    - name: Print File Paths
      ansible.builtin.debug:
        msg: "File Path: {{ item }}"
      loop: "{{ file_paths }}"

    - name: Copy the clear-softwaredistribution.ps1 script
      ansible.windows.win_copy:
        src: "C:\\projectresideo\\demofile"                             # Source directory containing the script template
        #src: "{{ lookup('file', '/path/to/demofile') }}"
        dest: "C:\\projectresideo\\os_patching_folder\\demofile1"
        remote_src: no
        mode: '0664' 

    - name: Copy Certificates
      win_copy:
        src: "{{ project_folder }}\\{{ item }}"
        dest: "{{ certificates_folder }}\\{{ item }}"
        remote_src: yes
      when: certificates_folder is defined and certificates_folder is not none
      loop: "{{ file_paths }}"
   
