- name: Ping test for windows clients
  hosts: all
  gather_facts: True
  #become: yes
  
  tasks:
    - name: ping
      win_ping:

    - name: Create os_patching directory
      file:
        path: "{{ os_patching_folder }}"
        state: directory
        recurse: yes
   
