- name: Ping test for windows clients
  hosts: all
  gather_facts: False
  #become: yes

  vars_files:
    - ./vars/ext_vars.yml  
  
  tasks:
    - name: ping
      win_ping:
    
    - name: Print File name
      ansible.builtin.debug:
        msg: "File Path1: {{ project_folder }}"
        msg: "File Path2: {{ os_patching_folder }}"

    - name: Create os_patching directory
      win_file:
        path: "{{ os_patching_folder }}"
        state: directory
        recurse: yes
   
